"use client";

import { summarizeNote } from "@/ai/flows/summarize-note";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { Copy, Download } from "lucide-react";
import { cn } from "@/lib/utils";

export default function Home() {
  const [note, setNote] = useState("");
  const [summary, setSummary] = useState("");
  const [isSummarizing, setIsSummarizing] = useState(false);
  const { toast } = useToast();

  const handleSummarize = async () => {
    setIsSummarizing(true);
    try {
      const result = await summarizeNote({ note });
      setSummary(result.summary);
      toast({
        title: "Summary Generated",
        description: "The summary has been successfully generated.",
      });
    } catch (error: any) {
      toast({
        variant: "destructive",
        title: "Error",
        description: error.message || "Failed to generate summary.",
      });
    } finally {
      setIsSummarizing(false);
    }
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([summary], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "summary.txt";
    document.body.appendChild(element); // Required for this to work in FireFox
    element.click();
  };

  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(summary);
    toast({
      description: "Summary copied to clipboard",
    });
  };

  return (
    <div className="flex flex-col items-center justify-start min-h-screen py-12 bg-background space-y-6">
      <h1 className="text-3xl font-semibold text-foreground">NoteFlow Summarizer</h1>

      <div className="w-full max-w-3xl space-y-4">
        <Card>
          <CardHeader>
            <CardTitle>Enter your note</CardTitle>
            <CardDescription>Paste a long note or paragraph to summarize.</CardDescription>
          </CardHeader>
          <CardContent>
            <Textarea
              placeholder="Paste your note here..."
              value={note}
              onChange={(e) => setNote(e.target.value)}
              className="resize-none shadow-sm"
            />
          </CardContent>
        </Card>

        <div className="flex justify-center">
          <Button
            onClick={handleSummarize}
            disabled={isSummarizing || !note}
            className="bg-accent text-accent-foreground hover:bg-teal-700 shadow-md"
          >
            {isSummarizing ? "Summarizing..." : "Summarize"}
          </Button>
        </div>

        {summary && (
          <Card>
            <CardHeader>
              <CardTitle>Summary</CardTitle>
              <CardDescription>Concise summary generated by AI.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="whitespace-pre-line">{summary}</div>
              <div className="flex justify-end space-x-2">
                <Button
                  variant="outline"
                  size="icon"
                  onClick={handleCopyToClipboard}
                  className="hover:bg-accent/10"
                >
                  <Copy className="h-4 w-4" />
                  <span className="sr-only">Copy to clipboard</span>
                </Button>
                <Button
                  variant="secondary"
                  onClick={handleDownload}
                  className="bg-secondary text-secondary-foreground hover:bg-secondary/80 shadow-sm"
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
